spring.application.name=demo
server.port=${PORT:1918}
spring.neo4j.uri=${COGNODB_URI}
spring.neo4j.authentication.username=${COGNODB_USERNAME}
spring.neo4j.authentication.password=${COGNODB_PASSWORD}
jooble.api.key=${JOOBLE_API_KEY}